### ISSUE TITLE
"Migrating" from the standard Nextcloud client to Snap

### ISSUE THREAD

**Issue by cilex-ft** [glasen/snap-nextcloud-desktop-client#11]
Hi,

I currently use the regular v 3.4.3 (Ubuntu Focal Ubuntu 20.04.5 LTS), but updating is not automatic via apt, so quite painful. How can I switch to your Snap version without losing my configurations and without having to restart syncing Gbs of files?

Also, I use Nemo file manager with nemo-nextcloud, not the regular Nautilus.

Thanks!

**Comment by glasen** [comment]
If you have no problems with the version from Ubuntu 20.04, and you don't need any of the new features, then you should stick with this version.

The problem with my snap-package and also the official AppImage-package from Nextcloud is that there is no integration in Nautilus/Nemo or other file-managers. Basically, the extensions would work, by creating a symlink on your own, but there will be no icons in Nautilus because you cannot set any path in the source code of the extension for them. Nautilus assumes that all icons and emblems are stored in "/usr/share/icons".
