### ISSUE TITLE
Log file cannot be opened for writting

### ISSUE THREAD

**Issue by vershart** [glasen/snap-nextcloud-desktop-client#5]
**Environment:** 

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

**App version:** nextcloud-desktop-client 3.4.4

**Steps to reproduce:** none
**Actual result:** 
Error message indicating that application cannot open log file for writing from time to time.

![image](https://user-images.githubusercontent.com/72304377/162590175-6262ff42-03ee-4606-9455-d62d9fd70fb1.png)
![image](https://user-images.githubusercontent.com/72304377/162590193-f9653bb0-17ea-4187-a499-f3464cc0cce6.png)

**Additional info:** nothing has been changed in app configuration in a while

**Comment by glasen** [comment]
This bug is triggered when the nextcloud-client snap is refreshed in the background. The client revision in your case was 48 and after the refresh it becomes 49 or higher. The problem is triggered because snap merges the config-dir from 48 the another and the running client cannot find the directory after a refresg
A restart of the client fixes the problem. I'm currently trying to find a way the restart of the client is triggered when a refresh occures.

**Comment by glasen** [comment]
Fixed the with the newest snap-package.
